version: "3.8"

services:
  nginx:
    image: nginx:1.14-alpine
    container_name: laravel-nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./src/public:/var/www/laravel/public
    ports:
      - "8000:80"
    depends_on:
      - phpfpm
    networks:
      - laravel-network

  phpfpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-phpfpm
    volumes:
      - ./src:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: profile
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_TEST_HOST: mysql_test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - mysql_test
      - redis
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    ports:
      - "3406:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profile
    networks:
      - laravel-network

  mysql_test:
    image: mysql:5.7
    container_name: laravel-mysql-test
    ports:
      - "3506:3306"
    volumes:
      - ./db_test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profile_test
    networks:
      - laravel-network

  redis:
    image: redis:5.0-alpine
    container_name: laravel-redis
    ports:
      - "46379:6379"
    networks:
      - laravel-network

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-mailhog
    ports:
      - "8025:8025"
      - "2525:1025"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
